name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker images
    - name: Build Docker images
      run: |
        docker build -t user-service-v1 ./user-service-v1
        docker build -t user-service-v2 ./user-service-v2
        docker build -t order-service ./order-service
        docker build -t api-gateway ./api-gateway

    # Step 4: Deploy to VM
    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Pull the latest changes
          cd ~/order-user-microservice
          git pull

          # Stop and remove old containers
          docker compose down

          # Rebuild and start containers
          docker compose up --build -d
